### ISSUE TITLE
Fails to run on JDK 17 javac

### ISSUE THREAD

**Issue by timothyg-stripe** [bazel-contrib/unused-jvm-deps#20]
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.Iterable com.sun.tools.javac.code.Scope$WriteableScope.getSymbols(com.sun.tools.javac.util.Filter)'
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitMethodInvocation(ImportedSymbolScanner.java:135)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitMethodInvocation(ImportedSymbolScanner.java:34)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1592)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitMethod(ImportedSymbolScanner.java:78)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitMethod(ImportedSymbolScanner.java:34)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitClass(ImportedSymbolScanner.java:70)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitClass(ImportedSymbolScanner.java:34)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitCompilationUnit(ImportedSymbolScanner.java:46)
	at com.stripe.build.dependencyanalyzer.plugin.ImportedSymbolScanner.visitCompilationUnit(ImportedSymbolScanner.java:34)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
	at com.stripe.build.dependencyanalyzer.plugin.StripeDependencyAnalyzerPlugin$1.finished(StripeDependencyAnalyzerPlugin.java:49)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:102)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
```

**Comment by kmensah-stripe** [comment]
It looks like  WritableScope.getSymbols no longer exists at head https://github.com/openjdk/jdk/blob/be3676f6bbc2d8041e43cf7bcfaee7fb9d864378/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Scope.java#L219

**Comment by kmensah-stripe** [comment]
https://github.com/openjdk/jdk/commit/657f10393745026c3a593872b8c37403dae3adc1#diff-6905d88c2b721f0d7476b1c6702b39ea5aba9836267ca39274e9021f8aa32db1R99 this PR changes this function from taking a Filter to taking a predicate.

I think the fix might be as simple as building against  a new JDK and publishing the artifact

**Comment by timothyg-stripe** [comment]
I wonder if we might need/want to do a [multi-release JAR](https://openjdk.org/jeps/238).

**Comment by kmensah-stripe** [comment]
I think the answer is to move away from using scope.java since it's an internal class with no stability guarantees https://github.com/openjdk/jdk/blob/master/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Scope.java#L51. 

Mostly notes for me: I spent today trying to dig into how things are getting confused. ct.sym doesn't have this symbol and  platformclasspath.jar has the version of this method that uses Predicate. My next guess is that because JavaBuilder targets JDK 8 and this error happens in a javac plugin, a classloader shared between JavaBuilder and the unused-jvm-dep plugin is getting confused
